### ISSUE TITLE
only accept commands from specified telegram clients 

### ISSUE THREAD

**Issue by tazinblack** [m0by314/raspberry_pi_home_security_system#1]
Sorry, I saw no other way to contact you.

To have a minimum security level it should be possible that the bot only accepts commands from specified telegram client ids.
Otherwise others could easily use your device to break your privacy.
It think some kind of id list as a textfile or something would be enough!

Thanks a lot and good work!

**Comment by m0by314** [comment]
Thank you for informing me of this security concern, I added a method to the Telebot class so that the bot only communicates with this chat_id
