### ISSUE TITLE
requirement is not longer available

### ISSUE THREAD

**Issue by strike19** [m0by314/raspberry_pi_home_security_system#2]
I just downloaded  your files and tried to install it.

Following failure occurred:
 --- Requirements installation ---
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting request==2019.4.13 (from -r requirements.txt (line 1))
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/request/

see also discussion:
https://stackoverflow.com/questions/62927162/no-matching-distribution-found-for-multiple-packages

The bot itself works, when I comment out "#request==2019.4.13" but it seem the PIR doesn't work anymore or what are the dependencies to this package?

Regards
Strike

**Comment by m0by314** [comment]
Hello Strike

I just made some modification. 
I deleted the request module, this fixed the error. 
You also need to fill in the CHAT_ID variable in lib/config.py.

How do you test the PIR?
Motion detection only works when the Bot is listening. You can see its status with the command /status

Regards

**Comment by strike19** [comment]
Seems the problem is solved thanks for the fast reply. PIR problem was between my ears... ;-)
